server:
  port: 8081

spring:
  profile: docker
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.23.0.3:3306/alura_spring_boot
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  boot:
    admin:
      client:
        url: 'http://172.23.0.2:8080'
        instance:
          service-base-url: 'http://172.23.0.2:8080'

token:
  secret: chavedotoken
  expiration: 86400000

#   actuator configuration
management:
  endpoint:
    info:
      enabled: true
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

