spring:
  profile: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alura_spring_boot
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
#this is for actuator monitinring this application.
#  boot:
#    admin:
#      client:
#        url: 'http://localhost:8081'

token:
  secret: chavedotoken
  expiration: 86400000

#   actuator configuration
management:
  endpoint:
    info:
      enabled: true
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

